on:
  push:
    branches: [ main ]
    
jobs:
  minify:
    runs-on: ubuntu-latest
    name: minify css

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: css
          output: css/min

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified css files"
          branch: ${{ github.ref }}
